### PR TITLE
GUACAMOLE-1205: Bump Guacamole manual versions to 1.3.0

### PR DESCRIPTION
**Pull request by necouchman**

### CODE REVIEW

**Review by mike-jumper — CHANGES_REQUESTED** [review]
Looks good, but what about `src/chapters/header-auth.xml`?

**Comment by mike-jumper** [comment]
> Looks good, but what about `src/chapters/header-auth.xml`?

Never mind - guacamole-auth-header wasn't touched. I'll rerun my checks. That shouldn't have turned up as having differences.

**Comment by mike-jumper** [comment]
OK, rerunning my checks, I see the following guacamole-client subprojects having been changed since 1.2.0:

* `guacamole/`
* `guacamole-common/`
* `guacamole-common-js/`
* `guacamole-ext/`
* `extensions/guacamole-auth-cas/`
* `extensions/guacamole-auth-duo/`
* `extensions/guacamole-auth-jdbc/`
* `extensions/guacamole-auth-openid/`
* `extensions/guacamole-auth-quickconnect/`
* `extensions/guacamole-auth-radius/`
* `extensions/guacamole-auth-totp/`

And the following are updated here (though they haven't technically changed yet) because they have pending PRs that are likely to be merged for release in 1.3.0:

* `extensions/guacamole-auth-ldap/` (#527)

I can't find any in-progress changes or issues for the following in 1.3.0:

* `extensions/guacamole-auth-saml/`

@necouchman, can you point to where guacamole-auth-saml is being touched for 1.3.0?

**Comment by necouchman** [comment]
> I can't find any in-progress changes or issues for the following in 1.3.0

@mike-jumper - For guacamole-auth-saml, guacamole-client/#513.

**Comment by mike-jumper** [comment]
Ah, OK then.

**Review by mike-jumper — APPROVED** [review]

**Pull request merged**
